"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# Use environment variables for configuration in production-ready deployments
import os
import ssl
from pathlib import Path

# Optional custom CA bundle (set CUSTOM_CA_PATH to absolute path to PEM file)
custom_ca = os.environ.get('CUSTOM_CA_PATH')
if custom_ca:
    try:
        ssl._create_default_https_context = ssl.create_default_context(cafile=custom_ca)
    except Exception:
        # fall back to system default if custom CA cannot be loaded
        pass

# MongoDB connection: prefer MONGO_URI env var for production (e.g. Atlas)
from mongoengine import connect, disconnect
import logging
disconnect(alias='default')
MONGO_URI = os.environ.get('MONGO_URI', 'mongodb://localhost:27017/customer_db')
try:
    # Use a short server selection timeout so startup fails fast when DB is unreachable
    connect(host=MONGO_URI, alias='default', serverSelectionTimeoutMS=5000)
except Exception as e:
    # Log a concise warning — avoid printing full URI in logs for security
    masked = MONGO_URI
    try:
        if '://' in MONGO_URI and not MONGO_URI.startswith('mongodb://localhost'):
            masked = MONGO_URI.split('://', 1)[0] + '://<REDACTED>'
    except Exception:
        masked = '<invalid-mongo-uri>'
    logging.warning("Could not connect to MongoDB at startup (MONGO_URI=%s): %s", masked, e)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from environment (set DJANGO_SECRET_KEY in production)
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-0ccmuq)_*j=#95)a!73cqkxm0ob^zjh_z*fu@u*(a^pzuhm8t9')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

# Hosts allowed to serve the application. Comma separated in env var.
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

DATABASES = {
    # Use a lightweight SQLite DB for Django internal apps (migrations, sessions, admin)
    # The application data (customers, orders) use mongoengine and connect to MongoDB separately.
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'app',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves static files efficiently in production
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # CORS middleware should be as high as possible
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# NOTE: mongoengine connection is configured at the top of this file so the
# application code using mongoengine Documents can access MongoDB.


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# For development, use console backend (prints emails to terminal)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production or real email sending, use Gmail SMTP backend
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your_gmail@gmail.com'   # Replace with your Gmail address
# EMAIL_HOST_PASSWORD = 'your_gmail_app_password' # Use Gmail App Password (not your regular password)


CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL', 'True').lower() in ('1', 'true', 'yes')
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
# Where `collectstatic` will collect static files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Use WhiteNoise storage for compressed/immutable files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Optionally set CORS_ALLOWED_ORIGINS via env var (comma separated)
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:4200,https://yourdomain.com').split(',')



LOGIN_DIRECT_URL = 'api/user/profile/'
LOGOUT_DIRECT_URL = 'api/logout/'
LOGIN_URL = 'api/login/'
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:4200').split(',')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

